"""add unique constraint on snapshot game_id+game_clock_seconds

Revision ID: 7b7d81f74b41
Revises: e40ac3f08341
Create Date: 2026-07-02 12:57:23.876484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7d81f74b41'
down_revision: Union[str, Sequence[str], None] = 'e40ac3f08341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_snapshot_game_clock', 'snapshots', ['game_id', 'game_clock_seconds'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_game_clock', 'snapshots', type_='unique')
    # ### end Alembic commands ###
