"""use video timestamp instead of ocr'd clock as snapshot dedup key

Revision ID: aea084e65cb0
Revises: 7b7d81f74b41
Create Date: 2026-07-02 14:12:25.885832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea084e65cb0'
down_revision: Union[str, Sequence[str], None] = '7b7d81f74b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('video_timestamp_seconds', sa.Float(), nullable=False))
    op.drop_constraint(op.f('uq_snapshot_game_clock'), 'snapshots', type_='unique')
    op.create_unique_constraint('uq_snapshot_game_video_timestamp', 'snapshots', ['game_id', 'video_timestamp_seconds'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_game_video_timestamp', 'snapshots', type_='unique')
    op.create_unique_constraint(op.f('uq_snapshot_game_clock'), 'snapshots', ['game_id', 'game_clock_seconds'], postgresql_nulls_not_distinct=False)
    op.drop_column('snapshots', 'video_timestamp_seconds')
    # ### end Alembic commands ###
