"""initial schema

Revision ID: e40ac3f08341
Revises: 
Create Date: 2026-07-02 11:42:32.044156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40ac3f08341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_league'), 'matches', ['league'], unique=False)
    op.create_index(op.f('ix_matches_video_id'), 'matches', ['video_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_league'), 'teams', ['league'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('blue_team_id', sa.String(), nullable=False),
    sa.Column('red_team_id', sa.String(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['blue_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['red_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_match_id'), 'games', ['match_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('ign', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('frame_path', sa.String(), nullable=False),
    sa.Column('game_clock_seconds', sa.Integer(), nullable=True),
    sa.Column('blue_gold', sa.Integer(), nullable=True),
    sa.Column('blue_kills', sa.Integer(), nullable=True),
    sa.Column('blue_towers', sa.Integer(), nullable=True),
    sa.Column('red_gold', sa.Integer(), nullable=True),
    sa.Column('red_kills', sa.Integer(), nullable=True),
    sa.Column('red_towers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_game_id'), 'snapshots', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_game_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_match_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_league'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_matches_video_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_league'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
